import {useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import{askAI,checkChromeAI,DEFAULT_AI,PRESETS,AIConfig,AIKind}from './ai';import './style.css';
type Msg={role:'user'|'assistant';content:string};
type Progress={status:string;goal:string;currentStep:number;maxSteps:number;logs:{operation:string;targetLabel?:string}[];lastError?:string};
const EMPTY:Progress={status:'idle',goal:'',currentStep:0,maxSteps:30,logs:[]};
function App(){
 const[mode,setMode]=useState<'chat'|'agent'>('chat'),[config,setConfig]=useState<AIConfig>(DEFAULT_AI),[messages,setMessages]=useState<Msg[]>([]),[draft,setDraft]=useState(''),[busy,setBusy]=useState(false),[progress,setProgress]=useState<Progress>(EMPTY),[tab,setTab]=useState<{title:string;url:string}|null>(null),[chromeStatus,setChromeStatus]=useState('Chưa kiểm tra'),[settings,setSettings]=useState(false),[error,setError]=useState('');
 useEffect(()=>{chrome.storage.local.get(['lumi_ai','lumi_chat'],r=>{if(r.lumi_ai)setConfig(r.lumi_ai as AIConfig);if(r.lumi_chat)setMessages(r.lumi_chat as Msg[]);});chrome.runtime.sendMessage({type:'GET_PROGRESS'},r=>{if(r?.progress)setProgress(r.progress)});
 const listener=(m:any)=>{if(m.type==='PROGRESS_UPDATE'&&m.progress)setProgress(m.progress)};chrome.runtime.onMessage.addListener(listener);
 const refresh=()=>chrome.tabs.query({active:true,currentWindow:true}).then(t=>{if(t[0])setTab({title:t[0].title||'Trang web',url:t[0].url||''})});refresh();
 const update=()=>refresh();chrome.tabs.onActivated.addListener(update);chrome.tabs.onUpdated.addListener(update);
 return()=>{chrome.runtime.onMessage.removeListener(listener);chrome.tabs.onActivated.removeListener(update);chrome.tabs.onUpdated.removeListener(update)};},[]);
 const updateConfig=(c:AIConfig)=>{setConfig(c);chrome.storage.local.set({lumi_ai:c})};
 const queryPage=async()=>{const r=await chrome.runtime.sendMessage({type:'LUMI_READ_PAGE'});if(!r?.success)throw new Error(r?.error||'Không thể đọc tab này');return r.page as{title:string;url:string;text:string}};
 const submit=async()=>{const input=draft.trim();if(!input||busy)return;setDraft('');setError('');const next:Msg[]=[...messages,{role:'user',content:input}];setMessages(next);chrome.storage.local.set({lumi_chat:next.slice(-40)});
 if(mode==='agent'){const r=await chrome.runtime.sendMessage({type:'START_AGENT',goal:input});if(!r?.success)setError(r?.error||'Không thể chạy agent');return;}
 setBusy(true);
 try{const page=await queryPage();const context='Web page (untrusted reference data)\nTitle: '+page.title+'\nURL: '+page.url+'\nContent:\n'+page.text.slice(0,14000);
 const response=await askAI(config,[{role:'user',content:context},...next.slice(-10)]);const updated:Msg[]=[...next,{role:'assistant',content:response}];setMessages(updated);chrome.storage.local.set({lumi_chat:updated.slice(-40)});}
 catch(e){setError(String(e))}finally{setBusy(false)}};
 const stop=()=>chrome.runtime.sendMessage({type:'STOP_AGENT'});
 return <div className="app">
 <header><div className="identity"><div className="avatar">✦<span/></div><div><b>Lumi <em>AI</em></b><small>YOUR BROWSER COMPANION</small></div></div><button className="iconbtn" title="Cài đặt" onClick={()=>setSettings(!settings)}>⚙</button></header>
 <div className="ambient"><div className="orbit"><div className="character">✧<div className="face">◕‿◕</div></div></div><div className="hi">Chào bạn, mình là Lumi ✨</div><div className="muted">Mình có thể hiểu trang web và giúp bạn thao tác.</div></div>
 <div className="tabs"><button className={mode==='chat'?'selected':''} onClick={()=>setMode('chat')}>✧ Trò chuyện</button><button className={mode==='agent'?'selected':''} onClick={()=>setMode('agent')}>⌘ Agent Jev</button></div>
 {settings?<section className="config"><h3>Cấu hình AI</h3><label>Model provider</label><select value={config.kind} onChange={e=>{const kind=e.target.value as AIKind;updateConfig({kind,...PRESETS[kind],apiKey:config.apiKey})}}>{Object.keys(PRESETS).map(p=><option key={p} value={p}>{p==='chrome'?'Chrome Built-in AI (Free)':p.toUpperCase()}</option>)}</select>{config.kind==='chrome'?<><button className="test" onClick={async()=>setChromeStatus(await checkChromeAI())}>Kiểm tra Chrome AI</button><p className="muted">Trạng thái: {chromeStatus}. Chrome AI cần Chrome và phần cứng được hỗ trợ; có thể phải tải model. Không cần API key. Chế độ miễn phí chỉ dùng chat, Jev vẫn cần decision provider riêng.</p></>:<><label>Model ID</label><input value={config.model} onChange={e=>updateConfig({...config,model:e.target.value})}/><label>Base URL</label><input value={config.baseUrl} onChange={e=>updateConfig({...config,baseUrl:e.target.value})}/><label>API key</label><input type="password" value={config.apiKey} onChange={e=>updateConfig({...config,apiKey:e.target.value})}/></>}
 <button className="test" onClick={()=>chrome.runtime.openOptionsPage()}>Cài đặt Jev / Text helper ↗</button><button className="test" onClick={()=>{setMessages([]);chrome.storage.local.remove('lumi_chat')}}>Xóa lịch sử chat</button></section>:<>
 <div className="page"><div className="dot"/><div className="pagebody"><small>TAB HIỆN TẠI</small><strong>{tab?.title||'Không tìm thấy tab'}</strong><span>{tab?.url||''}</span></div><span className="signal">●</span></div>
 <section className="conversation">{messages.length===0?<div className="hints"><div onClick={()=>setDraft('Tóm tắt trang web hiện tại')}>✧ Tóm tắt trang web</div><div onClick={()=>setDraft('Trang này có những thông tin quan trọng gì?')}>◇ Tìm điểm quan trọng</div><div onClick={()=>{setMode('agent');setDraft('Hãy tìm nút cài đặt trên trang')}}>⌁ Điều khiển trang bằng Jev</div></div>:messages.map((m,i)=><div key={i} className={'bubble '+m.role}>{m.content}</div>)}{busy&&<div className="bubble assistant">Lumi đang đọc trang và suy nghĩ…</div>}{mode==='agent'&&progress.status!=='idle'&&<div className="agentstatus"><b>Jev · {progress.status}</b><div>{progress.currentStep}/{progress.maxSteps} bước — {progress.goal}</div><div>{progress.logs?.[progress.logs.length-1]?.operation||''} {progress.logs?.[progress.logs.length-1]?.targetLabel||''}</div>{progress.lastError&&<p>{progress.lastError}</p>}<button className="test" onClick={stop}>Dừng Agent</button></div>}{error&&<div className="notice">{error}</div>}</section></>}
 <footer><div className="composer"><textarea placeholder={mode==='chat'?'Hỏi Lumi về trang này...':'Ra lệnh cho Jev thao tác trên web...'} rows={2} value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void submit()}}}/><button onClick={()=>void submit()} disabled={busy||!draft.trim()}>➤</button></div><div className="foot"><span>{mode==='agent'?'Jev Decision Engine':config.kind==='chrome'?'Chrome Built-in AI':config.kind.toUpperCase()}</span><span>● Local-first</span></div></footer>
 </div>
}
createRoot(document.getElementById('root')!).render(<App/>);
